"""add column summary

Revision ID: 1b0a6d3fcf9c
Revises: ec0e8dbad3c2
Create Date: 2023-11-26 11:23:40.768994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0a6d3fcf9c'
down_revision = 'ec0e8dbad3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
