"""add column toc

Revision ID: 7b38ad64ea18
Revises: c44279991e65
Create Date: 2023-11-29 22:33:17.203668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b38ad64ea18'
down_revision = 'c44279991e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('toc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'toc')
    # ### end Alembic commands ###
